import { StyleSheet } from 'react-native';

import { COLORS, MARKER_SIZES, UI_CONFIG } from '../constants';

export const emergencyTrackingHeaderStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.LIGHT_GRAY,
    backgroundColor: COLORS.OFF_WHITE,
  },
  backButton: {
    padding: 8,
    marginRight: 16,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  headerContent: {},
  brandRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  brandMark: {
    fontSize: 22,
    fontWeight: '900',
    color: COLORS.BLACK,
    letterSpacing: 4,
  },
  brandDot: {
    fontSize: 22,
    fontWeight: '900',
    color: COLORS.SIGNAL_RED,
    lineHeight: 26,
  },
  headerLine: {
    width: 30,
    height: 2,
    backgroundColor: COLORS.SIGNAL_RED,
    marginTop: 4,
    marginBottom: 4,
  },
  tagline: {
    fontSize: 9,
    fontWeight: '500',
    color: COLORS.MID_GRAY,
    letterSpacing: 2,
  },
});

export const emergencyTrackingMapStyles = StyleSheet.create({
  map: {
    flex: 1,
  },
  userMarker: {
    ...MARKER_SIZES.USER_MARKER,
    backgroundColor: COLORS.OFF_WHITE,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: UI_CONFIG.SHADOW_OFFSET,
    shadowOpacity: UI_CONFIG.SHADOW_OPACITY,
    shadowRadius: UI_CONFIG.SHADOW_RADIUS,
    elevation: UI_CONFIG.ELEVATION,
  },
  providerMarker: {
    ...MARKER_SIZES.PROVIDER_MARKER,
    backgroundColor: COLORS.MID_GRAY,
    justifyContent: 'center',
    alignItems: 'center',
  },
  assignedProviderMarker: {
    ...MARKER_SIZES.ASSIGNED_PROVIDER_MARKER,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: UI_CONFIG.SHADOW_OFFSET,
    shadowOpacity: UI_CONFIG.SHADOW_OPACITY,
    shadowRadius: UI_CONFIG.SHADOW_RADIUS,
    elevation: UI_CONFIG.ELEVATION,
  },
});

export const emergencyTrackingStatusCardUserStyles = StyleSheet.create({
  statusCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.OFF_WHITE,
    borderTopWidth: 1,
    borderTopColor: COLORS.LIGHT_GRAY,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    maxHeight: '40%',
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: COLORS.BLACK,
    marginBottom: 8,
  },
  typeBadgeText: {
    color: COLORS.OFF_WHITE,
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 6,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  statusSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
    letterSpacing: 1,
    color: COLORS.BLACK,
    textTransform: 'uppercase',
  },
  providersCount: {
    fontSize: 11,
    color: COLORS.MID_GRAY,
    marginBottom: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  routeInfoSwiss: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    gap: 16,
  },
  routeInfoSwissItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeInfoSwissText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.BLACK,
    marginLeft: 4,
    letterSpacing: 1,
  },
  routeInfoSwissDivider: {
    width: 1,
    height: 14,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  hairline: {
    height: 1,
    backgroundColor: COLORS.LIGHT_GRAY,
    marginBottom: 10,
  },
  providerInfo: {
    backgroundColor: COLORS.OFF_WHITE,
    borderTopWidth: 1,
    borderTopColor: COLORS.LIGHT_GRAY,
    paddingTop: 8,
    marginBottom: 8,
  },
  providerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  providerAvatar: {
    width: 36,
    height: 36,
    backgroundColor: COLORS.BLACK,
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerDetails: {
    flex: 1,
    marginLeft: 8,
  },
  providerName: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.BLACK,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  providerVehicle: {
    fontSize: 10,
    color: COLORS.MID_GRAY,
    letterSpacing: 0.5,
  },
  callButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    backgroundColor: COLORS.BLACK,
    marginTop: 12,
  },
  callButtonText: {
    color: COLORS.OFF_WHITE,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: COLORS.SIGNAL_RED,
    marginBottom: 8,
  },
  cancelButtonText: {
    color: COLORS.SIGNAL_RED,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  confirmArrivalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    backgroundColor: COLORS.SIGNAL_RED,
    marginBottom: 8,
  },
  confirmArrivalButtonText: {
    color: COLORS.OFF_WHITE,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  connectionText: {
    fontSize: 10,
    color: COLORS.MID_GRAY,
    letterSpacing: 1,
  },
});

export const emergencyTrackingStatusCardProviderStyles = StyleSheet.create({
  statusCard: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.OFF_WHITE,
    borderTopWidth: 1,
    borderTopColor: COLORS.LIGHT_GRAY,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    maxHeight: '40%',
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: COLORS.BLACK,
    marginBottom: 10,
  },
  typeBadgeText: {
    color: COLORS.OFF_WHITE,
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 6,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  roleBadge: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 8,
  },
  roleBadgeText: {
    color: COLORS.OFF_WHITE,
    fontSize: 9,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  statusSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
    letterSpacing: 1,
    color: COLORS.BLACK,
    textTransform: 'uppercase',
  },
  routeInfoSwiss: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    gap: 16,
  },
  routeInfoSwissItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeInfoSwissText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.BLACK,
    marginLeft: 4,
    letterSpacing: 1,
  },
  routeInfoSwissDivider: {
    width: 1,
    height: 14,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  hairline: {
    height: 1,
    backgroundColor: COLORS.LIGHT_GRAY,
    marginBottom: 10,
  },
  confirmArrivalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    backgroundColor: COLORS.SIGNAL_RED,
    marginBottom: 8,
  },
  confirmArrivalButtonText: {
    color: COLORS.OFF_WHITE,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  connectionText: {
    fontSize: 10,
    color: COLORS.MID_GRAY,
    letterSpacing: 1,
  },
});
