services:
  hospital_db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: resq_hospital
    ports:
      - '127.0.0.1:5542:5432'
    volumes:
      - hospital_postgres_data:/var/lib/postgresql/data

  hospital_redis:
    image: valkey/valkey
    restart: unless-stopped
    ports:
      - '127.0.0.1:6382:6379'

  hospital_backend:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    restart: unless-stopped
    environment:
      SECTOR: hospital
      PORT: 3000
      DEV_IP: 0.0.0.0
      DATABASE_URL: postgresql://root:admin123@hospital_db:5432/resq_hospital
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      REDIS_HOST: hospital_redis
      REDIS_PORT: 6379
      KAFKA_BROKERS: hospital_kafka:29092
    env_file:
      - ./silo.env
    depends_on:
      - hospital_db
      - hospital_redis
      - hospital_kafka
    ports:
      - '127.0.0.1:7402:3000'

    # Redis is used by OTP/MFA/locks.

  hospital_kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: unless-stopped
    ports:
      - '127.0.0.1:9095:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@hospital_kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095,PLAINTEXT_INTERNAL://hospital_kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - hospital_kafka_data:/var/lib/kafka/data

volumes:
  hospital_postgres_data:
  hospital_kafka_data:
